import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "../globals.css";
import Header from "../components/header";

const inter = Inter({subsets: ["latin"]});
export const metadata: Metadata = {
    title: "Next App",
    description: "Generated by Next and Me",
};
export default function MainLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col min-h-screen mx-auto max-w-[75%] px-4 pt-8 pb-16">
            <div className="flex-grow">
                <Header/>
                <main className="my-0 py-16">
                    {children}
                </main>
            </div>
        </div>
    );
}